import { useRef } from 'react';
import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, Upload, FileText, FolderOpen, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useCase } from '@/features/case';
import { Panel, SectionHeading, Status, metadata } from '@/features/ui';
export const Route=createFileRoute('/documents')({head:()=>metadata('Document Centre','Organize and track the documents needed across financial claims.'),component:Documents});
const docs=[['Death Certificate','Identity','Ready'],['PAN Card','Identity','Ready'],['Aadhaar Card','Identity','Ready'],['Bank Passbook','Bank','Uploaded'],['EPFO Form 20','EPFO','Required'],['EPFO Form 10D','EPFO','Required'],['EPFO Form 5IF','EPFO','Required'],['Insurance Policy','Insurance','Ready'],['Loan Statement','Loans','Required'],['Nomination Record','Legal heir documents','Required'],['Claimant ID','Identity','Missing'],['Legal Heir Certificate','Legal heir documents','Missing']] as const;
function Documents(){const {estate,uploaded,addUpload}=useCase();const input=useRef<HTMLInputElement>(null);return <><SectionHeading eyebrow="Organize" title="Document Centre" description="Document checklist generated from your estate. Keep the paperwork in one place." aside={<><input ref={input} type="file" className="hidden" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>{const file=e.target.files?.[0];if(file){addUpload(file.name);e.target.value=''}}}/><Button onClick={()=>input.current?.click()}><Upload/> Upload document</Button></>}/><div className="mb-7 grid grid-cols-2 gap-3 md:grid-cols-4">{[['12','documents organized'],['5','required'],['3','missing'],['4','ready']].map(([number,label])=><Panel key={label} className="p-5"><p className="text-2xl font-semibold">{number}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></Panel>)}</div><div className="mb-6 flex items-center gap-2 rounded-md bg-teal-soft px-4 py-3 text-xs text-teal"><FolderOpen className="size-4"/> {estate?.demo?'Fictional demo case. Files chosen here stay in this browser session only.':'Demo only: selected file names stay in this browser session; file contents are not stored.'}</div><div className="grid gap-6 lg:grid-cols-[1fr_280px]"><Panel className="overflow-hidden"><div className="border-b border-border p-5"><h2 className="font-semibold">Your checklist</h2><p className="mt-1 text-xs text-muted-foreground">Requirements may vary by institution and claim type.</p></div><div className="divide-y divide-border">{docs.map(([name,category,status])=><div key={name} className="flex flex-wrap items-center gap-3 px-5 py-4"><span className="flex size-9 shrink-0 items-center justify-center rounded bg-secondary text-teal"><FileText className="size-4"/></span><div className="min-w-[150px] flex-1"><p className="text-sm font-medium">{name}</p><p className="mt-1 text-xs text-muted-foreground">{category}</p></div><Status>{uploaded.includes(name)?'Uploaded':status}</Status></div>)}{uploaded.filter(name=>!docs.some(d=>d[0]===name)).map(name=><div key={name} className="flex items-center gap-3 px-5 py-4"><span className="flex size-9 items-center justify-center rounded bg-sage-soft text-sage"><CheckCircle2 className="size-4"/></span><span className="flex-1 truncate text-sm font-medium">{name}</span><Status>Uploaded</Status></div>)}</div></Panel><Panel className="h-fit p-5"><p className="eyebrow">A helpful reminder</p><h3 className="mt-3 font-semibold">Keep original documents safe.</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">Institutions may need to see originals even if you have copies organized here.</p><Button asChild variant="outline" size="sm" className="mt-5"><Link to="/claims">View claim guides <ArrowRight/></Link></Button></Panel></div></>}
