import { useState, type ReactNode } from 'react';
import { HelpCircle, X, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { meaning } from './case';

export function SectionHeading({eyebrow,title,description,aside}: {eyebrow?:string;title:string;description?:string;aside?:ReactNode}) { return <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div>{eyebrow && <p className="eyebrow mb-3">{eyebrow}</p>}<h1 className="page-title">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{aside}</div> }
export function Panel({children,className=''}:{children:ReactNode;className?:string}) { return <div className={`surface ${className}`}>{children}</div> }
export function Status({children}:{children:string}) { const tone = children==='Urgent'||children==='Missing'?'bg-amber-soft text-amber-ink':children==='Ready'||children==='Settled'||children==='Submitted'?'bg-sage-soft text-sage':children==='In progress'||children==='Documents gathering'||children==='Uploaded'?'bg-teal-soft text-teal':'bg-muted text-muted-foreground'; return <span className={`inline-flex items-center whitespace-nowrap rounded px-2.5 py-1 text-xs font-medium ${tone}`}>{children}</span> }
export function Term({children}:{children:string}) { const [open,setOpen]=useState(false); return <span className="relative inline-flex items-center gap-1"><span>{children}</span><Button variant="ghost" size="icon" className="h-5 w-5 text-muted-foreground" aria-label={`What does ${children} mean?`} onClick={()=>setOpen(!open)}><HelpCircle className="size-3.5"/></Button>{open && <span role="dialog" className="absolute top-7 left-0 z-30 w-64 rounded-md border border-border bg-card p-4 text-left text-xs font-normal leading-5 text-foreground shadow-xl"><span className="mb-1 flex items-center justify-between font-semibold">{children}<Button variant="ghost" size="icon" className="h-5 w-5" onClick={()=>setOpen(false)} aria-label="Close explanation"><X className="size-3"/></Button></span>{meaning(children)}</span>}</span> }
export function InlineAction({children,onClick}:{children:string;onClick:()=>void}) { return <Button variant="link" size="sm" onClick={onClick} className="px-0 text-teal">{children}<ArrowRight className="size-3.5"/></Button> }
export const metadata = (title:string, description:string) => ({ meta:[{title:`${title} | Claim Saathi`},{name:'description',content:description},{property:'og:title',content:`${title} | Claim Saathi`},{property:'og:description',content:description},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary'}] });
